# Generated by Django 3.2.11 on 2022-01-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='usercardcode',
            field=models.CharField(blank=True, db_column='userCardCode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uservalid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='a', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
