# Generated by Django 3.2.11 on 2022-02-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersign', '0002_auto_20220123_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimage',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
