# Generated by Django 3.2.11 on 2022-02-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersign', '0003_user_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authcard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
